# 错误边界

部分 UI 的 JS 错误不应该导致整个应用崩溃，为了解决整个问题，React 16 引入了这个新的概念——错误边界。

错误边界是一种 React 组件，这种组件可以捕获并打印发生其子组件树中任何位置的 JS 错误，并且，它会渲染出备用 UI，而不是渲染那些已经发生了错误的子组件树。错误边界在渲染期间、生命周期方法与整个组件树的构造函数中捕获错误。

> 但是要注意，错误边界无法捕获以下场景中产生的错误：
>
> + 事件处理
> + 异步代码
> + 服务端渲染
> + 它自身抛出的错误

直接引用官方文档上的这个例子：

如果一个 class 组件中定义了 static getDerivedStateFromError() 或 componentDidCatch() 这两个生命周期方法中的任意一个（或两个）时，那么它就变成一个错误边界。当抛出错误后，请使用 static getDerivedStateFromError() 渲染备用 UI ，使用 componentDidCatch() 打印错误信息。

```jsx
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {    // 更新 state 使下一次渲染能够显示降级后的 UI    
      return { hasError: true };  
  }
  
  componentDidCatch(error, errorInfo) {    // 你同样可以将错误日志上报给服务器    
      logErrorToMyService(error, errorInfo);  
  }
    
  render() {
    if (this.state.hasError) {      // 你可以自定义降级后的 UI 并渲染      
        return <h1>Something went wrong.</h1>;    
    }
    return this.props.children; 
  }
}
```

然后你可以将它作为一个常规组件去使用：

```jsx
<ErrorBoundary>
  <MyWidget />
</ErrorBoundary>
```

# 错误边界应该放置在何处？

可以将其与路由组件一样，放置在最顶层上，当组件产生问题时向用户展示一个 Something went wrong 的错误信息。

也可以将单独的组件包装在错误边界以保护整个应用的其他部分不会崩溃。

# 为捕获错误的新行为

自 React 16 起，任何未被错误边界捕获的错误将会导致整个 React 组件树被卸载。

# 关于 try/catch

try/catch 仅仅能用于命令式代码。但是 React 组件是声明式的并且必须具体指出是什么组件需要被渲染。

错误边界保留了 React 的生命性质，其行为符合你的预期。例如，即使一个错误发生在 componentDidUpdate 方法中，并且由某一个深层组件树的 setState 引起，其仍让能够冒泡到最近的错误边界。

# 关于事件处理器

错误边界无法捕获事件处理器内部的错误。

React 不需要错误边界来捕获事件处理器中的错误。与 render 方法和生命周期方法不同，事件处理器不会在渲染期间触发。因此，如果它们抛出异常，React 仍然能够知道需要在屏幕上显示什么。

如果你需要在事件处理器内部捕获错误，使用普通的 JavaScript try / catch 语句：
